### PR TITLE
Fix/percentage methods

### LINKED ISSUE #53: Fix Percentage Method Classes

### PR DESCRIPTION
**Pull request by grantdavis303**

### CODE REVIEW

**Review by Steddy1Love — APPROVED** [review]

File: lib/game.rb [hunk 1]
```diff
@@ -40,6 +40,36 @@ def self.all
...
   end
 
+  def self.percentage_home_wins
+    home_win_counter = 0
+    @@all.each do |game|
+      if game.home_goals > game.away_goals
+        home_win_counter += 1
+      end
+    end
+    (home_win_counter / @@all.length.to_f).round(2) # 3237 / 7441
```
Comment (wallacebilly1) [inline lib/game.rb:50]: We'll eventually want to get rid of the commented out portions before we turn in. But nice logic here.

**Review by wallacebilly1 — APPROVED** [review]
Nice job abstracting the methods into the class file.
